# Generated by Django 5.1.5 on 2025-02-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="imagelink",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
