# Generated by Django 5.1.5 on 2025-02-27 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_candidate_imagelink"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField(default=datetime.date(2025, 2, 27))),
                ("end_date", models.DateField(default=datetime.date(2025, 3, 1))),
            ],
        ),
        migrations.RenameField(
            model_name="voter",
            old_name="voter",
            new_name="user",
        ),
    ]
