# Generated by Django 5.1.5 on 2025-02-27 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_electionsetting_rename_voter_voter_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.post"
            ),
        ),
    ]
