# Generated by Django 5.1.5 on 2025-02-27 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_candidate_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="core.post"
            ),
        ),
    ]
